config/routes.rb
ResTechPlumbing::Application.routes.draw do

  # HomePages
  %w( home residential commercial products contact ).each do |page|
    match '/'+page, to: 'home_pages#'+page, via: 'get'
  end

  %w( pipe drain waterheater shower video toilet gas ).each do |page|
    match '/'+page, to: 'plumbing_pages#'+page, via: 'get'
  end

  root to: 'home_pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
  end

  def residential
  end

  def commercial
  end

  def products
  end

  def contact
  end
end

app/controllers/plumbing_pages_controller.rb
class PlumbingPagesController < ApplicationController
  def pipe
  end

  def drain
  end

  def waterheater
  end

  def shower
  end

  def video
  end

  def toilet
  end

  def gas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def nav_active(link_path)
  #   if link_path.kind_of?(Array)
  #     link_path.each do |path|
  #       class_name = ''
  #       if current_page?(path)
  #         class_name = 'active'
  #         return class_name
  #       end
  #     end
  #   else
  #     class_name = current_page?(link_path) ? 'active' : ''
  #   end
  #   class_name
  # end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/plumbing_pages_helper.rb
module PlumbingPagesHelper
end

app/views/home_pages/about.html.haml
.row.show-grid
  .col-md-12.col-sm-12
    .row.show-grid.clear-both
      / BEGIN LEFT-SIDEBAR
      #left-sidebar.col-md-3.col-sm-3.sidebar
        / LEFT-SIDEBAR: SIDEBAR NAVIGATION
        .side-nav.sidebar-block
          %h2 Learn More
          %ul
            %li.single{class: "#{nav_active(home_path)}"}
              = link_to "Home", home_path
            %li.single{class: "#{nav_active(about_path)}"}
              = link_to "About", about_path
            %li.single{class: "#{nav_active(residential_path)}"}
              = link_to "Residential", residential_path
            %li.single{class: "#{nav_active(commercial_path)}"}
              = link_to "Commercial", commercial_path
            %li.single{class: "#{nav_active(products_path)}"}
              = link_to "Products", products_path
      / END LEFT-SIDEBAR
      / BEGIN ARTICLE CONTENT AREA
      .col-md-6.col-sm-6.main-column.three-columns-central
        %article
          %h1 ABOUT US
          %p Aenean lacinia bibendum nulla sed consectetur. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          / %img.bordered-img.img-responsive{:alt => "", :src => "img/about-us.jpg"}/
          %p Donec ullamcorper nulla non metus auctor fringilla. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui.
          %p Donec ullamcorper nulla non metus auctor fringilla. Sed posuere consectetur est at lobortis. Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper. Nullam quis risus eget urna mollis ornare vel eu leo.
          %p Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.
          %p Aenean lacinia bibendum nulla sed consectetur. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      / END ARTICLE CONTENT AREA
      / BEGIN RIGHT-SIDEBAR
      #right-sidebar.col-md-3.col-sm-3.sidebar
        / RIGHT-SIDEBAR: TEXT WIDGET AREA
        .text-widget.sidebar-block
          %h2 Text Widget
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Donec ullamcorper nulla non metus auctor fringilla. Donec id elit non mi porta gravi
        / RIGHT-SIDEBAR: TAGS WIDGET AREA
        / .tags-widget.sidebar-block
        /   %h2 Tags
        /   %ul
        /     %li
        /       %p
        /         %i.icon-tags
        /         %a{:href => "#"} blog
        /     %li
        /       %p
        /         %i.icon-tags
        /         %a{:href => "#"} photo
        /     %li
        /       %p
        /         %i.icon-tags
        /         %a{:href => "#"} news
        /     %li
        /       %p
        /         %i.icon-tags
        /         %a{:href => "#"} business
        /     %li
        /       %p
        /         %i.icon-tags
        /         %a{:href => "#"} commercial
        /     %li
        /       %p
        /         %i.icon-tags
        /         %a{:href => "#"} design
        / / RIGHT-SIDEBAR: GALLERY WIDGET AREA
        / .gallery-widget.sidebar-block
        /   %h2 Gallery Widget
        /   %ul
        /     %li
        /       %a.photo{:href => "#"}
        /         %img{:alt => "", :src => "img/blog-widget01.jpg"}/
        /     %li
        /       %a.photo{:href => "#"}
        /         %img{:alt => "", :src => "img/blog-widget02.jpg"}/
        /     %li
        /       %a.photo{:href => "#"}
        /         %img{:alt => "", :src => "img/blog-widget03.jpg"}/
        /     %li
        /       %a.photo{:href => "#"}
        /         %img{:alt => "", :src => "img/blog-widget04.jpg"}/
        /     %li
        /       %a.photo{:href => "#"}
        /         %img{:alt => "", :src => "img/blog-widget05.jpg"}/
        /     %li
        /       %a.photo{:href => "#"}
        /         %img{:alt => "", :src => "img/blog-widget06.jpg"}/
      / END RIGHT-SIDEBAR

app/views/home_pages/commercial.html.haml
.row
	.col-md-12.col-sm-12
		.row.show-grid.clear-both
			/ BEGIN ARTICLE CONTENT AREA
			.col-sm-8.col-sm-offset-2.center-column
				%article
					%h1
						=fa_icon "building-o lg", class: "pull-right"
						COMMERCIAL SERVICES
					.text-divider1
					%ul.fa-ul.restech-list
						%li
							= fa_icon "star li", class: ""
							1 Hour Priority Service
						%li
							= fa_icon "star li", class: ""
							Preventative Maintenance Programs
						%li
							= fa_icon "star li", class: ""
							Personalized Service
						%li
							= fa_icon "star li", class: ""
							Drain Cleaning & Hydro-jetting Services
						%li
							= fa_icon "star li", class: ""
							Video Pipe Inspection & Leak Detection
						%li
							= fa_icon "star li", class: ""
							24 Hour Emergeny Serivce
						%li
							= fa_icon "star li", class: ""
							Grease Trap Pumping & Cleaning
						%li
							= fa_icon "star li", class: ""
							Expert Plumbing & Repair Technicians
					%p Get Professional Priority Service From	ResTech Plumbing & Drains
					%p Get real savings and professional service when you open an account with ResTech Plumbing & Drains. When you call on us we give you an On Time Service Guarantee and Special Rate Pricing.
					%p Let ResTech Plumbing & Drains Save You Time & Money
					%p We offer preventative maintenance programs and 24 hour emergency service to meet your needs, and our preventative maintenance programs can save you time and money. We guarantee our work between scheduled maintenances. (see terms and conditions)
					%p
						Free Estimates... ResTech Plumbing & Drains
						&nbsp;
						= link_to "(951) 737-5800", "tel:951-737-5800"

app/views/home_pages/contact.html.haml
.row
	.col-md-12.col-sm-12
		.row.show-grid.clear-both
			/ BEGIN ARTICLE CONTENT AREA
			.col-sm-8.col-sm-offset-2.center-column
				%article.contact
					%h1
						=fa_icon "comments lg", class: "pull-right"
						CONTACT
					.text-divider1
					%p
						For 24/7 Emergency Service Call:
					%p
						=fa_icon "phone lg", class: "pull-left"
						%b
							&nbsp;
							= link_to "(951) 737-5800", "tel:951-737-5800"
					.text-divider1
					%p
						For all customer service questions and inquiries contact:
					%p
						=fa_icon "envelope lg", class: "pull-left"
						%b
							&nbsp;							
							= mail_to "restechpd@yahoo.com"
					.text-divider1
					%p	
						Leave us a review on:
						%p
							&nbsp;
							=fa_icon "star", class: "pull-left"
							=fa_icon "star", class: "pull-left"
							=fa_icon "star", class: "pull-left"
							=fa_icon "star", class: "pull-left"
							=fa_icon "star", class: "pull-left"
						%p
							%b
								= link_to "Yelp", "http://www.yelp.com/biz/restech-plumbing-and-drains-norco", class: "display-inline", target: '_blank'
							or
							%b
								= link_to "YP", "http://www.yellowpages.com/norco-ca/mip/restech-plumbing-and-drain-465317947", class: "display-inline", target: '_blank'

app/views/home_pages/home.html.haml
.row
  / MAIN CONTENT AREA: IMAGE and BLOCK
  .col-sm-12.col-md-12
    .bannercontainer
      .banner
        .row
          .col-sm-7.col-md-7
            = image_tag "istock/plumber-at-work.jpg", alt: "Hands with wrench fixing pipe", class: "img-fullwidth thumbnail"
          .col-sm-5.col-md-5
            .grey-box.hero-block-2
              %h1
                THE TRUSTED PLUMBING EXPERTS
              %p
                = fa_icon "wrench 4x", class: "text-muted pull-left"
                ResTech Plumbing and Drains is the name you can depend on for fast, professional service.
              .clear
                = link_to contact_path, class: "btn btn-warning btn-lg" do
                  FREE ESTIMATE
  .row.main-block.index1
    .col-sm-12.col-md-12
      / MAIN CONTENT AREA: HERO LIST
      .row.show-grid.hero-list
        .col-sm-6.col-md-3
          .image-wrapper
            .img
              = fa_icon "exclamation-triangle 3x inverse"
          .image-text
            %h2 Emergency Service
            %p
              ResTech has the fast and honest Technicians you need to fix your emergency
          .clear
        .col-sm-6.col-md-3
          .image-wrapper
            .img
              = fa_icon "clock-o 3x inverse"
          .image-text
            %h2 Available 24/7
            %p
              ResTech Service Technicians are available to help day & night, 7 days a week
          .clear
        .col-sm-6.col-md-3
          .image-wrapper
            .img
              = fa_icon "thumbs-o-up 3x inverse"
          .image-text
            %h2 Trusted & Recommended
            %p
              ResTech comes
              %b
                = link_to "highly recommended", "http://www.yelp.com/biz/restech-plumbing-and-drains-norco", class: "display-inline", target: '_blank'
              by our customers
          .clear
        .col-sm-6.col-md-3
          .image-wrapper
            .img
              = fa_icon "check 3x inverse"
          .image-text
            %h2 Licensed & Insured
            %p
              ResTech is fully licensed and insured, so there is zero liability for homeowners
          .clear

app/views/home_pages/products.html.haml
.row
	.col-md-12.col-sm-12
		.row.show-grid.clear-both
			/ BEGIN ARTICLE CONTENT AREA
			.col-sm-8.col-sm-offset-2.center-column
				%article
					%h1
						=fa_icon "leaf lg", class: "pull-right"
						DRAIN PRODUCTS
					.text-divider1
					%p ResTech Plumbing & Drains uses only the highest quality of natural drain cleaner products. That's why we trust Drainbo® which offers quality products that are all natural, nontoxic and 100% safe to the environment. 
					= image_tag "drainbo.jpg", alt: "Drainbo Products", class: "img-fullwidth thumbnail"

					%blockquote
						%p The Drainbo® Team is a team of experts that have been solving your drain cleaning and plumbing issues since 1947. As our business grew, so did our customers needs. That's why we created Drainbo® Natural Drain Cleaner.
						%p And we are proud to say that our product not only works but Drainbo® is nontoxic, all natural, and completely safe for the environment. And Drainbo® Natural Drain Cleaner is easy to use, economical, and has a fresh lemon scent.
						%p
							Our natural drain cleaner and grease trap products work safely in your home and on our planet.
							%p.autor
								= link_to "//www.drainbo.com", title: "Drainbo Website", class: "", target: "_blank" do
									Drainbo.com
					%p  Just ask your Service Tech or call us and we'll be happy to deliver Drainbo® products right to your door at no additional cost.

app/views/home_pages/residential.html.haml
.row
	.col-md-12.col-sm-12
		.row.show-grid.clear-both
			/ BEGIN ARTICLE CONTENT AREA
			.col-sm-8.col-sm-offset-2.center-column
				%article
					/ %span.fa-stack.fa-3x
					/ 	=fa_icon "circle stack-2x", class: ""
					/ 	=fa_icon "home stack-1x inverse", class: ""
					%h1
						=fa_icon "home lg", class: "pull-right"
						RESIDENTIAL SERVICES
					.text-divider1
					%ul.fa-ul.restech-list
						%li
							= fa_icon "star li", class: ""
							Pipe Leaks & Slab Leaks
						%li
							= fa_icon "star li", class: ""
							Drain Stoppages & Sewer Repair
						%li
							= fa_icon "star li", class: ""
							Water Heater Install & Repair
						%li
							= fa_icon "star li", class: ""
							Shower Valve Repair & Replace
						%li
							= fa_icon "star li", class: ""
							Video Pipe Inspection & Leak Detection
						%li
							= fa_icon "star li", class: ""
							Toilet Repair & Replace
						%li
							= fa_icon "star li", class: ""
							Gas Line Repair & Replace
						%li
							= fa_icon "star li", class: ""
							Garbage Disposal & Diswasher Installs
					%p
						Call Us For A Free Estimate!
						&nbsp;
						= link_to "(951) 737-5800", "tel:951-737-5800"

app/views/layouts/_footer.html.haml
%footer#footer
  .footer-wrapper
    .container
      .row.show-grid
        .col-sm-12.col-md-12
          .row.show-grid
            / FOOTER: ABOUT US
            .col-sm-5.col-sm-offset-1.footer-center
              %h4 ABOUT
              %ul.footer-list
                %li
                  <i>R</i>eliable <i>E</i>xceptional <i>S</i>ervice <i>TECH</i>nicians
                %li Serving Riverside, San Bernardino & Los Angeles Counties
                %li 24/7 Emergency Service
                %li
                  Call
                  = link_to "(951) 737-5800", "tel:951-737-5800"              
            / FOOTER: REVIEWS
            .col-sm-5
              %h4.center-title REVIEWS
              .row
                .col-xs-5.col-xs-offset-1.col-sm-6.col-sm-offset-0
                  = link_to "http://www.yelp.com/biz/restech-plumbing-and-drains-norco", class: "", target: "_blank" do
                    = image_tag("yelp.svg", alt: "ResTech Yelp Reviews", title: "ResTech Yelp Reviews", class: "yelp-logo review-logo")
                .col-xs-3.col-xs-offset-1.col-sm-4.col-sm-offset-1
                  = link_to "http://www.yellowpages.com/norco-ca/mip/restech-plumbing-and-drain-465317947", class: "", target: "_blank" do
                    = image_tag("yp.svg", alt: "ResTech Yellow Pages Reviews", title: "ResTech Yellow Pages Reviews", class: "yp-logo review-logo")
  .footer-top
  .footer-bottom
    .container
      .row.show-grid
        / FOOTER: COPYRIGHT TEXT
        .col-sm-12.col-md-12.text-center
          %p
            ©
            #{Time.now.year}
            = link_to 'ResTech Plumbing and Drains', root_path
            

app/views/layouts/_header.html.haml
.header-wrapper
  / THE LINE AT THE VERY TOP OF THE PAGE
  .top_line
  / HEADER AREA
  %header
    .container
      .row
        / HEADER: LOGO AREA
        .col-sm-5.col-md-4.logo
          = link_to home_path, class: 'logo' do
            = image_tag("logo.png", alt: "ResTech Plumbing and Drains logo surrounded by stars", title: "ResTech Plumbing and Drains")
        .col-sm-6.col-sm-offset-1.col-md-5.col-md-offset-3.head_phone
          / HEADER: PHONE NUMBER BUTTON
          .call-btn
            = link_to "tel:951-737-5800", class: "btn btn-lg btn-danger" do
              = fa_icon "phone lg inverse"
              &nbsp; (951) 737-5800
          .location
            Serving
            = succeed ',' do
              %b Riverside
            %b San Bernardino
            %br>
            &
            %b Los Angeles
            Counties
    / HEADER: PRIMARY SITE NAVIGATION
    = render 'layouts/navigation'

app/views/layouts/_messages.html.haml
/ # Rails flash messages styled for Bootstrap 3.0
/ - flash.each do |name, msg|
/   - if msg.is_a?(String)
/     %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
/       %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
/       = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
/ navigation styled for Bootstrap 3.0
#nav-wrapper
  %nav.navbar.navbar-default
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %ul.nav.collapse.navbar-collapse.clear.nav-justified
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li.single
  = link_to home_path do
    HOME
    %i page
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => ""}
    PLUMBING
    %i
      information
      = fa_icon "chevron-down"
  %ul.dropdown-menu
    %li
      = link_to "Pipe Leaks & Slab Leaks", home_path
      /pipe_path
    %li
      = link_to "Drain Stoppages & Sewer Repair", home_path
      /drain_path
    %li
      = link_to "Water Heater Install & Repair", home_path
      /waterheater_path
    %li
      = link_to "Shower Valve Repair & Replace", home_path
      /shower_path
    %li
      = link_to "Video Pipe Inspection & Leak Detection", home_path
      /video_path
    %li
      = link_to "Toilet Repair & Replace", home_path
      /toilet_path
    %li
      = link_to "Gas Line Repair & Replace", home_path
      /gas_path
%li.single
  = link_to residential_path do
    RESIDENTIAL
    %i services
%li.single
  = link_to commercial_path do
    COMMERCIAL
    %i services
%li.single
  = link_to products_path do
    DRAIN
    %i products
%li.single
  = link_to contact_path do
    CONTACT
    %i call today!

app/views/layouts/_recent_tweets.html.haml
/ MAIN CONTENT AREA: bizstrap CUSTOM - RECENT TWEETS BAR
/ .recent-tweets
/   .container
/     .row.show-grid
/       .col-sm-12.col-md-12.twitter-wrapper
/         #nav_t
/         .tweets-slide
/           %ul.slides
/         %a.follow_img{:href => "#"}
/           %img.img-responsive{:alt => "", :src => "img/follow.png"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'ResTech Plumbing and Drains'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'ResTech Plumbing and Drains'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag '//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.background-pattern
    #over
      #out_container.boxed-attached
        = render 'layouts/header'
        %main.main-content{:role => "main"}
          .container
            = yield
        = render 'layouts/footer'

app/views/plumbing_pages/drain.html.haml
%h1 DRAIN STOPPAGES AND SEWER REPAIR

app/views/plumbing_pages/gas.html.haml
%h1 GAS

app/views/plumbing_pages/pipe.html.haml
%h1 PIPE LEAKS & SLAB LEAKS
/ .row
/   .col-md-12.col-sm-12
/     .row.show-grid.clear-both
/       / BEGIN LEFT-SIDEBAR
/       #left-sidebar.col-md-3.col-sm-3.sidebar
/         / LEFT-SIDEBAR: SIDEBAR NAVIGATION
/         .side-nav.sidebar-block
/           %h2 Why ResTech?
/           %ul
/             %li
/               = fa_icon "check"
/               Complete Plumbing & Drain Services
/             %li
/               = fa_icon "check"
/               Available 24 Hours / 7 Days a Week
/             %li
/               = fa_icon "check"
/               Emergency Service
/             %li
/               = fa_icon "check"
/               Licensed & Insured Technicians
/             %li
/               = fa_icon "check"
/               Millions of Satisfied Customers
/             %li
/               = fa_icon "check"
/               State-of-the-Art Equipment
/             %li
/               = fa_icon "check"
/               Reputation for Quality Work
/             %li
/               = fa_icon "check"
/               No Job is Too Big or Too Small
/             %li
/               = fa_icon "check"
/               Trusted & Recommended Since 1935
/       / END LEFT-SIDEBAR
/       / BEGIN ARTICLE CONTENT AREA
/       .col-md-6.col-sm-6.main-column.three-columns-central
/         %article
/           %h1 PIPE LEAKS & SLAB LEAKS
/           %p
/             Our well-known jingle says it all: When you trust Roto-Rooter, your plumbing and drain problems are solved—fast! We are licensed and insured, and our uniformed and badged technicians drive Roto-Rooter vehicles that are fully-stocked with necessary equipment and tools.
/             All plumbers are not equal. Roto-Rooter is North America’s #1 plumbing repair and drain service company. Homeowners everywhere have relied on Roto-Rooter since 1935 for honest, professional advice on all types of plumbing and drain cleaning services. Large jobs or small, we do it all:
/             = image_tag "istock/plumber-at-work.jpg", alt: "Sink Repair", class: "img-fullwidth thumbnail"
/           %p
/             More people depend on Roto-Rooter than any other company for residential plumbing and drain cleaning services. Our professional plumbers deliver fast, dependable service and will arrive uniformed and badged, driving a Roto-Rooter vehicle.
/             Check out Plumbing Basics for helpful videos and advice about your home's plumbing, seasonal plumbing tips, conservation tips, frequently asked plumbing questions and much more.
/             *All services may not be available from all locations
/           %ul.icons

/           %p Donec ullamcorper nulla non metus auctor fringilla. Sed posuere consectetur est at lobortis. Curabitur blandit tempus porttitor. Donec ullamcorper nulla non metus auctor fringilla. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper. Nullam quis risus eget urna mollis ornare vel eu leo.
/           %p Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vestibulum id ligula porta felis euismod semper.
/           %p Aenean lacinia bibendum nulla sed consectetur. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/       / END ARTICLE CONTENT AREA
/       / BEGIN RIGHT-SIDEBAR
/       #right-sidebar.col-md-3.col-sm-3.sidebar
/         / RIGHT-SIDEBAR: TEXT WIDGET AREA
/         .text-widget.sidebar-block
/           %h2 Text Widget
/           %p
/             Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Donec ullamcorper nulla non metus auctor fringilla. Donec id elit non mi porta gravi
/         / RIGHT-SIDEBAR: TAGS WIDGET AREA
/         / .tags-widget.sidebar-block
/         /   %h2 Tags
/         /   %ul
/         /     %li
/         /       %p
/         /         %i.icon-tags
/         /         %a{:href => "#"} blog
/         /     %li
/         /       %p
/         /         %i.icon-tags
/         /         %a{:href => "#"} photo
/         /     %li
/         /       %p
/         /         %i.icon-tags
/         /         %a{:href => "#"} news
/         /     %li
/         /       %p
/         /         %i.icon-tags
/         /         %a{:href => "#"} business
/         /     %li
/         /       %p
/         /         %i.icon-tags
/         /         %a{:href => "#"} commercial
/         /     %li
/         /       %p
/         /         %i.icon-tags
/         /         %a{:href => "#"} design
/         / / RIGHT-SIDEBAR: GALLERY WIDGET AREA
/         / .gallery-widget.sidebar-block
/         /   %h2 Gallery Widget
/         /   %ul
/         /     %li
/         /       %a.photo{:href => "#"}
/         /         %img{:alt => "", :src => "img/blog-widget01.jpg"}/
/         /     %li
/         /       %a.photo{:href => "#"}
/         /         %img{:alt => "", :src => "img/blog-widget02.jpg"}/
/         /     %li
/         /       %a.photo{:href => "#"}
/         /         %img{:alt => "", :src => "img/blog-widget03.jpg"}/
/         /     %li
/         /       %a.photo{:href => "#"}
/         /         %img{:alt => "", :src => "img/blog-widget04.jpg"}/
/         /     %li
/         /       %a.photo{:href => "#"}
/         /         %img{:alt => "", :src => "img/blog-widget05.jpg"}/
/         /     %li
/         /       %a.photo{:href => "#"}
/         /         %img{:alt => "", :src => "img/blog-widget06.jpg"}/
/       / END RIGHT-SIDEBAR

app/views/plumbing_pages/shower.html.haml
%h1 SHOWER

app/views/plumbing_pages/toilet.html.haml
%h1 TOILET

app/views/plumbing_pages/video.html.haml
%h1 VIDEO

app/views/plumbing_pages/waterheater.html.haml
%h1 WATERHEATER